### ISSUE TITLE
repr(C, align(...)) no longer working with bytemuck_derive 1.2.0

### ISSUE THREAD

**Issue by lassade** [Lokathor/bytemuck#129]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cb57c04750b013fa16ae9b85c5fb8127

I'm currently using this as a workaround:

```toml
bytemuck = { version = "=1.10.0", features = ["derive"] }
bytemuck_derive = "=1.1.0" # necessary
```
